-- CHỨC NĂNG PHÂN HỆ NHÂN VIÊN
use QL_NHAKHOA
GO
-- XEM THONG TIN --
-- XEM LICH KHÁM
CREATE OR ALTER PROC SP_NV_XEMLICHKHAM
AS
BEGIN
	SELECT *
	FROM V_LICHDATKHAM_NHANVIEN 
END
GO
-- XEM LICH LAM VIEC 
CREATE OR ALTER PROC SP_NV_XEMLICHLAMVIEC
AS
BEGIN
	SELECT *
	FROM V_LICHLAMVIEC_NHANVIEN
END
GO
-- XEM TT HOADON -- 
CREATE OR ALTER PROC SP_NV_XEMHOADON
AS
BEGIN
	SELECT *
	FROM V_HOADON_NHANVIEN
END
GO
-- XEM THONG TIN THUOC
CREATE OR ALTER PROC SP_NV_XEMTTTHUOC
AS
BEGIN
	SELECT * 
	FROM V_DANHMUC_THUOC 
END
GO
-- XEM THUOC SD -- 
CREATE OR ALTER PROC SP_NV_XEMDANHMUC_THUOCSD
AS
BEGIN
	SELECT * 
	FROM V_DANHMUC_THUOCSD 
END
GO
-- XEM DVSD -- 
CREATE OR ALTER PROC SP_NV_XEMDICHVU_SD
AS
BEGIN
	SELECT * 
	FROM V_DICHVU_SD
END
GO

-- UPDATE / INSERT -- 
-- INSERT - UPDATE LICHKHAM + LICHLAMVIEC THEO MAKH VA NGAYKHAM GIOKHAM KHACH HANG CUNG CAP
CREATE OR ALTER PROC SP_NV_THEMLICHKHAM
    @ID_KH VARCHAR(255),
    @ID_NV VARCHAR(255),
    @NGAYKHAM DATE,
    @GIOKHAM TIME
AS
BEGIN
    BEGIN TRAN;

    DECLARE @ID_LLV VARCHAR(255)
    DECLARE @TRANGTHAI VARCHAR(10)

    BEGIN
        IF EXISTS (
            SELECT 1
            FROM V_LICHLAMVIEC_NHANVIEN
            WHERE NGAYKHAM = @NGAYKHAM AND GIOKHAM = @GIOKHAM AND TRANGTHAI = N'Trống'
        )
        BEGIN
            -- Lấy ID_LLV từ lịch làm việc
            SELECT @ID_LLV = ID_LLV, @TRANGTHAI = TRANGTHAI
            FROM V_LICHLAMVIEC_NHANVIEN
            WHERE NGAYKHAM = @NGAYKHAM AND GIOKHAM = @GIOKHAM AND TRANGTHAI = N'Trống'

            BEGIN
                INSERT INTO LICH_DAT_KHAM (ID_LLV, ID_KH, ID_NV)
                VALUES (@ID_LLV, @ID_KH, @ID_NV)

                /*UPDATE LICH_LAM_VIEC
                SET TRANGTHAI = N'Đã Đặt'*/

                COMMIT TRAN;
                PRINT 'Lịch đặt khám đã được thêm thành công.'
            END
        END
        ELSE
        BEGIN
            ROLLBACK TRAN;
            PRINT 'Lịch làm việc đã được đặt.'
        END
    END
END
GO


-- INSERT --
-- INSERT HOA DON -- 
CREATE OR ALTER PROC SP_NV_LAPHOADON
	@ID_NV VARCHAR(255),
	@ID_BA VARCHAR(255)
AS
BEGIN
    BEGIN TRAN;

    DECLARE @TONGTIEN MONEY
    DECLARE @TONGTIENTHUOC MONEY
    DECLARE @TONGTIENDV MONEY

    SELECT @TONGTIENTHUOC = SUM(THANHTIEN_THUOC)
    FROM V_DANHMUC_THUOCSD 
    WHERE @ID_BA = ID_BA

    SELECT @TONGTIENDV = THANHTIEN
    FROM V_DICHVU_SD
    WHERE ID_BA = @ID_BA

    SET @TONGTIEN = @TONGTIENTHUOC + @TONGTIENDV

    DECLARE @ID_HOADON VARCHAR(255);
    SET @ID_HOADON = 'HD' + REPLACE(CONVERT(VARCHAR, GETDATE(), 112), '-', '') + RIGHT('0000' + CAST((SELECT COUNT(*) + 1 FROM HOA_DON) AS VARCHAR), 4);

    BEGIN TRY
        INSERT INTO V_HOADON_NHANVIEN (ID_HOADON, ID_NV, ID_BA, TONGTIEN, TONGTIENTHUOC, TONGTIENDV)
        VALUES (@ID_HOADON, @ID_NV, @ID_BA, @TONGTIEN, @TONGTIENTHUOC, @TONGTIENDV);

		UPDATE DICHVU_SD
        SET ID_HOADON = @ID_HOADON
        WHERE ID_BA = @ID_BA;

        SELECT 
            THUOC.TENTHUOC, 
            THUOC_SD.SOLUONG, 
            THUOC.GIATIEN, 
            THUOC_SD.SOLUONG * THUOC.GIATIEN AS THANHTIEN 
        FROM 
            THUOC_SD
        JOIN 
            THUOC ON THUOC_SD.ID_THUOC = THUOC.ID_THUOC
        WHERE 
            THUOC_SD.ID_BA = @ID_BA;

        COMMIT TRAN;
        PRINT 'Hoá đơn đã được tạo thành công!';
    END TRY
    BEGIN CATCH
        ROLLBACK TRAN;
        PRINT 'Đã xảy ra lỗi trong quá trình xử lý hoá đơn.';
    END CATCH
END
GO


