-- CHỨC NĂNG PHÂN HỆ NHÂN VIÊN
use QL_NHAKHOA
GO

CREATE OR ALTER PROC SP_NV_XEMLICHKHAM
AS
BEGIN
	SELECT *
	FROM LICH_DAT_KHAM
END
GO

CREATE OR ALTER PROC SP_NV_THEMLICHKHAM
	@ID_KH VARCHAR(255),
	@ID_NV VARCHAR(255)
AS
BEGIN	
	DECLARE @TRANGTHAI NVARCHAR(10);

    DECLARE @ID_LLV VARCHAR(255);
    SET @ID_LLV = 'LLV' + REPLACE(CONVERT(VARCHAR, GETDATE(), 112), '-', '') + RIGHT('0000' + CAST((SELECT COUNT(*) + 1 FROM LICH_LAM_VIEC) AS VARCHAR), 4);


	SELECT @TRANGTHAI = TRANGTHAI
    FROM LICH_LAM_VIEC
    WHERE ID_LLV = @ID_LLV;
	IF @TRANGTHAI IS NOT NULL AND @TRANGTHAI = 'Trống'

	BEGIN
        -- LỊCH LÀM VIỆC CÓ TRẠNG THÁI TRỐNG, THÊM LỊCH KHÁM
        INSERT INTO LICH_DAT_KHAM (ID_LLV, ID_KH, ID_NV)
        VALUES (@ID_LLV, @ID_KH, @ID_NV);

        -- CẬP NHẬT LẠI TRẠNG THÁI CỦA LỊCH LÀM VIỆC
        UPDATE LICH_LAM_VIEC
        SET TRANGTHAI = 'Đã Đặt'
        WHERE ID_LLV = @ID_LLV;

        PRINT 'Thêm lịch khám thành công!';
    END
	ELSE 
	BEGIN
		PRINT('Nha sĩ trên hiện không làm việc vào thời gian này!', 16, 1)
		RETURN
	END
END
GO


CREATE OR ALTER PROC SP_NV_LAPHOADON
	@ID_NV VARCHAR(255),
	@ID_BA VARCHAR(255)
AS
BEGIN
    -- Khai báo biến để lưu tổng tiền
    DECLARE @TONGTIEN MONEY;

    -- Tính tổng tiền từ các dịch vụ sử dụng
    SELECT @TONGTIEN = SUM(THANHTIEN)
    FROM DICHVU_SD
    WHERE ID_BA = @ID_BA;


    -- Thêm hoá đơn vào bảng HOA_DON
    DECLARE @ID_HOADON VARCHAR(255);
    SET @ID_HOADON = 'HD' + REPLACE(CONVERT(VARCHAR, GETDATE(), 112), '-', '') + RIGHT('0000' + CAST((SELECT COUNT(*) + 1 FROM HOA_DON) AS VARCHAR), 4);

	INSERT INTO HOA_DON (ID_HOADON, ID_NV, ID_BA, TONGTIEN)
    VALUES (@ID_HOADON, @ID_NV, @ID_BA, @TONGTIEN);

	UPDATE THUOC_SD
    SET THANHTIEN = Giatien * SOLUONG
    FROM THUOC_SD
    JOIN THUOC ON THUOC_SD.ID_THUOC = THUOC.ID_THUOC
    WHERE THUOC_SD.ID_BA = @ID_BA;

    -- In ra danh sách các thuốc đã sử dụng
    SELECT THUOC.TENTHUOC, THUOC_SD.SOLUONG, THUOC.GIATIEN, THUOC_SD.THANHTIEN
    FROM THUOC_SD
    JOIN THUOC ON THUOC_SD.ID_THUOC = THUOC.ID_THUOC
    WHERE THUOC_SD.ID_BA = @ID_BA;

    PRINT 'Hoá đơn đã được tạo thành công!';
END
GO

CREATE OR ALTER PROC SP_NV_XEMTTTHUOC
AS
BEGIN
	SELECT * 
	FROM THUOC
END
GO