﻿-- CHỨC NĂNG PHÂN HỆ NHA SĨ
use QL_NHAKHOA
GO
-- XEM THÔNG TIN --
-- 1. XEM TT CÁ NHÂN
CREATE OR ALTER PROC SP_NS_XEM_TTCANHAN
AS
BEGIN
    SELECT *
    FROM V_TKNHASI
END
GO

-- 2. XEM BENH AN BENH NHAN
CREATE OR ALTER PROC SP_NS_XEM_BENHAN
    @ID_BENHNHAN VARCHAR(255)
AS
BEGIN
    SELECT *
    FROM BENH_AN
    WHERE ID_KH = @ID_BENHNHAN
END
GO

-- 6. XEM THUOC -- 
CREATE OR ALTER PROC SP_NS_XEM_THUOC
AS
BEGIN
    SELECT *
    FROM V_XEM_THUOC
END
GO

-- 9. XEM LỊCH LÀM VIỆC
CREATE OR ALTER PROCEDURE SP_NS_XEM_LICHLAMVIEC
AS
BEGIN
    SELECT *
    FROM LICH_LAM_VIEC
    WHERE ID_NS = CURRENT_USER
        AND NGAYKHAM = GETDATE() 
END
GO

-- UPDATE / INSERT -- 
-- 1. UPDATE THONG TIN CA NHAN
CREATE OR ALTER PROC SP_NS_SUA_TTCANHAN
	@tentaikhoan NVARCHAR(30) = NULL,
	@ngaysinh DATE = NULL,
	@email VARCHAR(30) = NULL
AS

BEGIN TRAN
	DECLARE @idtaikhoan VARCHAR(255)
	SET @idtaikhoan = CURRENT_USER

	IF (LEN(ISNULL(@tentaikhoan, '')) = 0)
		BEGIN
			SET @tentaikhoan = (SELECT HOTEN FROM TAI_KHOAN WHERE ID_TAIKHOAN = @idtaikhoan)
		END

	IF (LEN(ISNULL(@ngaysinh, '')) = 0)
		BEGIN
			SET @ngaysinh = (SELECT NGAYSINH FROM TAI_KHOAN WHERE ID_TAIKHOAN = @idtaikhoan)
		END

	IF (LEN(ISNULL(@email, '')) = 0)
		BEGIN
			SET @email = (SELECT EMAIL FROM TAI_KHOAN WHERE ID_TAIKHOAN = @idtaikhoan)
		END

	UPDATE V_TKNHASI
	SET HOTEN = @tentaikhoan,
		NGAYSINH = @ngaysinh,
		EMAIL = @email
	WHERE ID_TAIKHOAN = @idtaikhoan
			
	IF (@@ERROR <> 0)
		BEGIN
			RAISERROR (N'Không thể cập nhật. Vui lòng thử lại', 0, 0)
			ROLLBACK TRAN
			RETURN
		END
COMMIT TRAN
GO
	
-- 3. INSERT BENH AN 
CREATE OR ALTER PROC SP_NS_THEM_BENHAN
	@ID_KH VARCHAR(255),
	@NGAYKHAM DATE
AS
BEGIN TRAN
	-- TAO ID BENH AN
	DECLARE @ID_BA VARCHAR(255)
	EXEC sp_TAOID @ID_BA OUTPUT
	-- GAN ID NHA SI
	DECLARE @ID_NS VARCHAR(255)
	SET @ID_NS = CURRENT_USER

	INSERT INTO V_THEM_BENHAN(
											ID_BA,
											ID_KH,
											ID_NS,
											NGAYKHAM)

	VALUES									(@ID_BA,
											@ID_KH,
											@ID_NS,
											@NGAYKHAM)
	IF (@@ERROR <> 0)
		BEGIN
			RAISERROR (N'Không thể thêm. Vui lòng thử lại', 0, 0)
			ROLLBACK TRAN
			RETURN
		END
COMMIT TRAN
GO

-- 4. INSERT DICH VU SD CHO BENH AN
CREATE OR ALTER PROC SP_NS_THEM_DICHVUSD
	@ID_LOAIDV VARCHAR(255),
	@THANHTIEN MONEY,
	@ID_HOADON VARCHAR(255),
	@ID_BA VARCHAR(255)
AS
BEGIN TRAN
	DECLARE @ID_DVSD VARCHAR(255)
	EXEC sp_TAOID @ID_DVSD OUTPUT

	IF (LEN(ISNULL(@ID_LOAIDV, '')) = 0)
		BEGIN
			SET @ID_LOAIDV = (SELECT ID_LOAIDV FROM DICHVU_SD WHERE ID_BA = @ID_BA)
		END	

	IF (LEN(ISNULL(@THANHTIEN, '')) = 0)
		BEGIN
			SET @THANHTIEN = (SELECT THANHTIEN FROM DICHVU_SD WHERE ID_BA = @ID_BA)
		END	

	IF (LEN(ISNULL(@ID_HOADON, '')) = 0)
		BEGIN
			SET @ID_HOADON = (SELECT ID_HOADON FROM DICHVU_SD WHERE ID_BA = @ID_BA)
		END	

	IF (@@ERROR <> 0)
		BEGIN
			RAISERROR (N'Không thể thêm. Vui lòng thử lại', 0, 0)
			ROLLBACK TRAN
			RETURN
		END
COMMIT TRAN
GO

-- 5. INSERT LOAI DICH VU
CREATE OR ALTER PROC SP_NS_THEM_LOAIDICHVU
	@TENDV NVARCHAR(30),
	@GIATIEN MONEY
AS
BEGIN TRAN
	-- TAO ID LOAI DICH VU
	DECLARE @ID_LOAIDV VARCHAR(255)
	EXEC sp_TAOID @ID_LOAIDV OUTPUT

	INSERT INTO V_THEM_BENHAN(
											ID_LOAIDV,
											TENDV,
											GIATIEN)

	VALUES									(@ID_LOAIDV,
											@TENDV,
											@GIATIEN)
	IF (@@ERROR <> 0)
		BEGIN
			RAISERROR (N'Không thể thêm. Vui lòng thử lại', 0, 0)
			ROLLBACK TRAN
			RETURN
		END
COMMIT TRAN
GO

-- 7. INSERT THUOC SD CHO BENH AN
CREATE OR ALTER PROC SP_NS_THEM_THUOC_SD
	@ID_BA VARCHAR(255),
	@ID_THUOC VARCHAR(255),
	@SOLUONG INT
AS
BEGIN TRAN
	IF (LEN(ISNULL(@ID_THUOC, '')) = 0)
		BEGIN
			SET @ID_THUOC = (SELECT ID_THUOC FROM THUOC_SD WHERE ID_BA = @ID_BA)
		END

	IF (LEN(ISNULL(@SOLUONG, '')) = 0)
		BEGIN
			SET @SOLUONG = (SELECT SOLUONG FROM THUOC_SD WHERE ID_BA = @ID_BA)
		END

	IF (@@ERROR <> 0)
		BEGIN
			RAISERROR (N'Không thể thêm. Vui lòng thử lại', 0, 0)
			ROLLBACK TRAN
			RETURN
		END
COMMIT TRAN
GO

-- 8. UPDATE LICH LAM VIEC
CREATE OR ALTER PROC SP_NS_SUA_LICHLAMVIEC
	@ID_LLV VARCHAR(255),
	@NGAYKHAM DATE,
	@GIOKHAM TIME,
	@TRANGTHAI NVARCHAR(10)
AS
BEGIN TRAN
	DECLARE @ID_NS VARCHAR(255)
	SET @ID_NS = CURRENT_USER

	IF (LEN(ISNULL(@NGAYKHAM, '')) = 0)
		BEGIN
			SET @NGAYKHAM = (SELECT NGAYKHAM FROM LICH_LAM_VIEC WHERE ID_LLV = @ID_LLV)
		END

	IF (LEN(ISNULL(@GIOKHAM, '')) = 0)
		BEGIN
			SET @GIOKHAM = (SELECT GIOKHAM FROM LICH_LAM_VIEC WHERE ID_LLV = @ID_LLV)
		END

	IF (LEN(ISNULL(@TRANGTHAI, '')) = 0)
		BEGIN
			SET @TRANGTHAI = (SELECT TRANGTHAI FROM LICH_LAM_VIEC WHERE ID_LLV = @ID_LLV)
		END

	UPDATE V_XEM_THEM_SUA_LICHLAMVIEC
	SET NGAYKHAM = @NGAYKHAM,
		GIOKHAM = @GIOKHAM,
		TRANGTHAI = @TRANGTHAI
	WHERE ID_LLV = @ID_LLV

	IF (@@ERROR <> 0)
		BEGIN
			RAISERROR (N'Không thể cập nhật. Vui lòng thử lại', 0, 0)
			ROLLBACK TRAN
			RETURN
		END
COMMIT TRAN
GO

-- 8. INSERT LICH LAM VIEC
CREATE OR ALTER PROC SP_NS_THEM_LICHLAMVIEC
	@NGAYKHAM DATE,
	@GIOKHAM TIME,
	@TRANGTHAI NVARCHAR(10)
AS
BEGIN TRAN
	DECLARE @ID_LLV VARCHAR(255)
	EXEC sp_TAOID @ID_LLV OUTPUT
	DECLARE @ID_NS VARCHAR(255)
	SET @ID_NS = CURRENT_USER

	IF (LEN(ISNULL(@NGAYKHAM, '')) = 0)
		BEGIN
			SET @NGAYKHAM = (SELECT NGAYKHAM FROM LICH_LAM_VIEC WHERE ID_LLV = @ID_LLV)
		END

	IF (LEN(ISNULL(@GIOKHAM, '')) = 0)
		BEGIN
			SET @GIOKHAM = (SELECT GIOKHAM FROM LICH_LAM_VIEC WHERE ID_LLV = @ID_LLV)
		END

	IF (LEN(ISNULL(@TRANGTHAI, '')) = 0)
		BEGIN
			SET @TRANGTHAI = (SELECT TRANGTHAI FROM LICH_LAM_VIEC WHERE ID_LLV = @ID_LLV)
		END
	IF (@@ERROR <> 0)
		BEGIN
			RAISERROR (N'Không thể thêm. Vui lòng thử lại', 0, 0)
			ROLLBACK TRAN
			RETURN
		END
COMMIT TRAN
GO