USE QL_NHAKHOA
GO

EXEC sp_addrole 'QUAN_TRI_VIEN'
GO

--Thêm, xóa, sửa thông tin tài khoản nha sĩ, nhân viên

CREATE OR ALTER VIEW V_THEM_XOA_SUA_TKNHASI_NHANVIEN
AS
	SELECT*
	FROM TAI_KHOAN TK
GO

--Xem thông tin tất cả các loại tài khoản

CREATE OR ALTER VIEW V_XEM_TTTK
AS
	SELECT*
	FROM TAI_KHOAN TK
GO

--Xem, thêm, sửa, xóa thông tin thuốc

CREATE OR ALTER VIEW V_XEM_THEM_SUA_XOA_TTTHUOC
AS
	SELECT*
	FROM THUOC
GO

--Xem, thêm, sửa, xóa số lượng tồn kho

CREATE OR ALTER VIEW V_XEM_THEM_SUA_XOA_SOLUONGTONKHO
AS
	SELECT*
	FROM SO_LUONG_TON_KHO
GO

--Xem, thêm, sửa, xóa thuốc sử dụng 

CREATE OR ALTER VIEW V_XEM_THEM_SUA_XOA_THUOCSD
AS
	SELECT*
	FROM THUOC_SD
GO

GRANT INSERT, UPDATE, DELETE ON V_THEM_XOA_SUA_TKNHASI_NHANVIEN TO QUAN_TRI_VIEN

GRANT SELECT ON V_XEM_TTTK TO QUAN_TRI_VIEN

GRANT SELECT, INSERT, UPDATE, DELETE ON V_XEM_THEM_SUA_XOA_TTTHUOC TO QUAN_TRI_VIEN

GRANT SELECT, INSERT, UPDATE, DELETE ON V_XEM_THEM_SUA_XOA_SOLUONGTONKHO TO QUAN_TRI_VIEN

GRANT SELECT, INSERT, UPDATE, DELETE ON V_XEM_THEM_SUA_XOA_THUOCSD TO QUAN_TRI_VIEN

