USE QL_NHAKHOA
GO

EXEC sp_addrole 'NHA_SI'
GO

CREATE OR ALTER VIEW V_TKNHASI
AS
	SELECT*
	FROM TAI_KHOAN TK
	WHERE TK.ID_TAIKHOAN = CURRENT_USER
GO

CREATE OR ALTER VIEW V_TT_BENHNHAN
AS
	SELECT *
	FROM TAI_KHOAN TK
	WHERE TK.LOAITK = 'KH'
GO

CREATE OR ALTER VIEW V_THEM_BENH_AN
AS
	SELECT *
	FROM BENH_AN
GO

CREATE OR ALTER VIEW V_TT_LOAI_DICHVU
AS
	SELECT *
	FROM LOAI_DV
GO

CREATE OR ALTER VIEW V_GHI_DICHVU_SD
AS
	SELECT DVSD.*
	FROM DICHVU_SD DVSD
GO

CREATE OR ALTER VIEW V_XEM_THUOC
AS
	SELECT *
	FROM THUOC
GO

CREATE OR ALTER VIEW V_KEDONTHUOC
AS
	SELECT TSD.*
	FROM THUOC_SD TSD
GO

CREATE OR ALTER VIEW V_XEM_THEM_SUA_LICHLAMVIEC
AS
	SELECT LLV.*
	FROM LICH_LAM_VIEC LLV, TAI_KHOAN TK
	WHERE LLV.ID_NS = TK.ID_TAIKHOAN
		AND TK.ID_TAIKHOAN = CURRENT_USER
		AND LLV.NGAYKHAM = GETDATE()
GO

GRANT SELECT, UPDATE ON V_TKNHASI TO NHA_SI

GRANT SELECT ON V_TT_BENHNHAN TO NHA_SI

GRANT SELECT, INSERT ON V_THEM_BENH_AN TO NHA_SI

GRANT SELECT, INSERT ON V_TT_LOAI_DICHVU TO NHA_SI

GRANT SELECT, INSERT ON V_GHI_DICHVU_SD TO NHA_SI

GRANT SELECT ON V_XEM_THUOC TO NHA_SI

GRANT SELECT, INSERT ON V_KEDONTHUOC TO NHA_SI

GRANT SELECT, INSERT, UPDATE ON V_XEM_THEM_SUA_LICHLAMVIEC TO NHA_SI

GO