USE QL_NHAKHOA
GO

EXEC sp_addrole 'QUAN_TRI_VIEN'
GO

--Thêm, sửa thông tin tài khoản nha sĩ, nhân viên

CREATE OR ALTER VIEW V_THEM_SUA_TKNHASI_NHANVIEN
AS
	SELECT*
	FROM TAI_KHOAN TK
	WHERE TK.LOAITK = 'NS'
		OR TK.LOAITK = 'NV'
GO

--Xem thông tin tất cả các loại tài khoản

CREATE OR ALTER VIEW V_XEM_TTTK
AS
	SELECT*
	FROM TAI_KHOAN TK
GO

--Xem, thêm, sửa thông tin thuốc

CREATE OR ALTER VIEW V_XEM_THEM_SUA_XOA_TTTHUOC
AS
	SELECT*
	FROM THUOC T
GO

GRANT INSERT, UPDATE ON V_THEM_SUA_TKNHASI_NHANVIEN TO QUAN_TRI_VIEN

GRANT SELECT ON V_XEM_TTTK TO QUAN_TRI_VIEN

GRANT SELECT, INSERT, UPDATE, DELETE ON V_XEM_THEM_SUA_XOA_TTTHUOC TO QUAN_TRI_VIEN

