USE MASTER
GO

IF DB_ID('QL_NHAKHOA') IS NOT NULL --KTR CSDL QLLOPHOC TỒN TẠI CHƯA
	DROP DATABASE QL_NHAKHOA --XÓA CSDL
	GO
CREATE DATABASE QL_NHAKHOA --TẠO CSDL
GO

USE QL_NHAKHOA
GO

CREATE TABLE TAI_KHOAN(
	ID_TAIKHOAN VARCHAR(255) NOT NULL,
	HOTEN NVARCHAR(30),
	SDT CHAR(11) UNIQUE,
	NGAYSINH DATE,
	EMAIL VARCHAR(30),
	MATKHAU VARCHAR(30),
	LOAITK NVARCHAR(20),
	ID_QTV VARCHAR(255),
	CONSTRAINT pk_TAI_KHOAN PRIMARY KEY(ID_TAIKHOAN),
)
GO

CREATE TABLE QUAN_TRI_VIEN(
	ID_QTV VARCHAR(255) NOT NULL,
	ID_TAIKHOAN VARCHAR(255) UNIQUE,
	CONSTRAINT pk_QUAN_TRI_VIEN PRIMARY KEY(ID_QTV),
)
GO

CREATE TABLE NHAN_VIEN(
	ID_NV VARCHAR(255) NOT NULL,
	ID_TAIKHOAN VARCHAR(255) UNIQUE,
	CONSTRAINT pk_NHAN_VIEN PRIMARY KEY(ID_NV),
)
GO

CREATE TABLE NHA_SI(
	ID_NS VARCHAR(255) NOT NULL,
	ID_TAIKHOAN VARCHAR(255) UNIQUE,
	CONSTRAINT pk_NHA_SI PRIMARY KEY(ID_NS),
)
GO

CREATE TABLE KHACH_HANG(
	ID_KH VARCHAR(255) NOT NULL,
	ID_TAIKHOAN VARCHAR(255) UNIQUE,
	CONSTRAINT pk_KHACH_HANG PRIMARY KEY(ID_KH),
)
GO

CREATE TABLE DON_THUOC(
	ID_DONTHUOC VARCHAR(255) NOT NULL,
	ID_BA VARCHAR (255),
	THANHTIEN MONEY,
	ID_HOADON VARCHAR(255),
	CONSTRAINT pk_DON_THUOC PRIMARY KEY(ID_DONTHUOC),
)
GO

CREATE TABLE THUOC_SD(
	ID_DONTHUOC VARCHAR(255) NOT NULL,
	ID_THUOC VARCHAR(255),
	SOLUONG INT,
	CONSTRAINT pk_THUOC_SD PRIMARY KEY(ID_DONTHUOC,ID_THUOC),
)
GO

CREATE TABLE THUOC(
	ID_THUOC VARCHAR(255) NOT NULL,
	TENTHUOC NVARCHAR(30),
	CHIDINH NVARCHAR(100),
	NGAYHETHAN DATE,
	GIATIEN MONEY,
	ID_QTV VARCHAR(255),
	CONSTRAINT pk_THUOC PRIMARY KEY(ID_THUOC),
)
GO

CREATE TABLE SO_LUONG_TON_KHO(
	ID_THUOC VARCHAR(255) NOT NULL,
	SOLUONG INT,
	CONSTRAINT pk_SO_LUONG_TON_KHO PRIMARY KEY(ID_THUOC),
)
GO

CREATE TABLE HOA_DON(
	ID_HOADON VARCHAR(255) NOT NULL,
	ID_NV VARCHAR(255),
	ID_BA VARCHAR(255),
	TONGTIEN MONEY,
	CONSTRAINT pk_HOA_DON PRIMARY KEY(ID_HOADON),
)
GO

CREATE TABLE BENH_AN(
	ID_BA VARCHAR(255) NOT NULL,
	ID_KH VARCHAR(255),
	ID_NS VARCHAR(255),
	NGAYKHAM DATE,
	CONSTRAINT pk_BENH_AN PRIMARY KEY(ID_BA),
)
GO

CREATE TABLE LICH_DAT_KHAM(
	ID_LLV VARCHAR(255) NOT NULL,
	ID_KH VARCHAR(255),
	ID_NV VARCHAR(255),
	CONSTRAINT pk_LICH_DAT_KHAM PRIMARY KEY(ID_LLV,ID_KH),
)
GO

CREATE TABLE LICH_LAM_VIEC(
	ID_LLV VARCHAR(255) NOT NULL,
	NGAYKHAM DATE,
	GIOKHAM TIME,
	TRANGTHAI NVARCHAR(10),
	ID_NS VARCHAR(255),
	CONSTRAINT pk_LICH_LAM_VIEC PRIMARY KEY(ID_LLV),
)
GO

CREATE TABLE LOAI_DV(
	ID_LOAIDV VARCHAR(255) NOT NULL,
	TENDV NVARCHAR(30),
	GIATIEN MONEY,
	CONSTRAINT pk_LOAI_DV PRIMARY KEY(ID_LOAIDV),
)
GO

CREATE TABLE DICHVU_SD(
	ID_DVSD VARCHAR(255) NOT NULL,
	ID_LOAIDV VARCHAR(255),
	THANHTIEN MONEY,
	ID_HOADON VARCHAR(255),
	ID_BA VARCHAR(255),
	CONSTRAINT pk_DICHVU_SD PRIMARY KEY(ID_DVSD),
)
GO

ALTER TABLE TAI_KHOAN 
	ADD CONSTRAINT fk_TAI_KHOAN__QUAN_TRI_VIEN 
	FOREIGN KEY(ID_QTV) REFERENCES QUAN_TRI_VIEN(ID_TAIKHOAN)
	
GO
ALTER TABLE KHACH_HANG
	ADD CONSTRAINT fk_KHACH_HANG__TAI_KHOAN FOREIGN KEY (ID_TAIKHOAN) REFERENCES TAI_KHOAN(ID_TAIKHOAN)

GO

ALTER TABLE QUAN_TRI_VIEN
	ADD CONSTRAINT fk_QUAN_TRI_VIEN__TAI_KHOAN 
	FOREIGN KEY(ID_TAIKHOAN) REFERENCES TAI_KHOAN(ID_TAIKHOAN)

GO

ALTER TABLE NHAN_VIEN
	ADD CONSTRAINT fk_NHANVIEN__TAI_KHOAN 
	FOREIGN KEY(ID_TAIKHOAN) REFERENCES TAI_KHOAN(ID_TAIKHOAN)

GO

ALTER TABLE NHA_SI
	ADD CONSTRAINT fk_NHASI__TAI_KHOAN 
	FOREIGN KEY(ID_TAIKHOAN) REFERENCES TAI_KHOAN(ID_TAIKHOAN)

GO

ALTER TABLE SO_LUONG_TON_KHO
	ADD CONSTRAINT fk_SO_LUONG_TON_KHO__THUOC 
	FOREIGN KEY(ID_THUOC) REFERENCES THUOC(ID_THUOC)
GO

ALTER TABLE THUOC
	ADD CONSTRAINT fk_THUOC__QUAN_TRI_VIEN 
	FOREIGN KEY(ID_QTV) REFERENCES QUAN_TRI_VIEN(ID_QTV)
GO

ALTER TABLE THUOC_SD
	ADD CONSTRAINT fk_THUOC_SD__THUOC 
	FOREIGN KEY(ID_THUOC) REFERENCES THUOC(ID_THUOC)
GO

ALTER TABLE THUOC_SD
	ADD CONSTRAINT fk_THUOC_SD__DON_THUOC 
	FOREIGN KEY(ID_DONTHUOC) REFERENCES DON_THUOC(ID_DONTHUOC)
GO

ALTER TABLE DON_THUOC
	ADD CONSTRAINT fk_DON_THUOC__BENH_AN
	FOREIGN KEY(ID_BA) REFERENCES BENH_AN(ID_BA)
GO

ALTER TABLE DON_THUOC
	ADD CONSTRAINT fk_DON_THUOC__HOA_DON
	FOREIGN KEY(ID_HOADON) REFERENCES HOA_DON(ID_HOADON)
GO

ALTER TABLE HOA_DON
	ADD CONSTRAINT fk_HOA_DON__BENH_AN
	FOREIGN KEY(ID_BA) REFERENCES BENH_AN(ID_BA)
GO

ALTER TABLE HOA_DON
	ADD CONSTRAINT fk_HOA_DON__NHAN_VIEN
	FOREIGN KEY(ID_NV) REFERENCES NHAN_VIEN(ID_NV)
GO

ALTER TABLE BENH_AN
	ADD CONSTRAINT fk_BENH_AN__KHACH_HANG
	FOREIGN KEY(ID_KH) REFERENCES KHACH_HANG(ID_KH)
GO

ALTER TABLE BENH_AN
	ADD CONSTRAINT fk_BENH_AN__NHA_SI
	FOREIGN KEY(ID_NS) REFERENCES NHA_SI(ID_NS)
GO

ALTER TABLE DICHVU_SD
	ADD CONSTRAINT fk_DICHVU_SD__LOAI_DV
	FOREIGN KEY(ID_LOAIDV) REFERENCES LOAI_DV(ID_LOAIDV)
GO

ALTER TABLE DICHVU_SD
	ADD CONSTRAINT fk_DICHVU_SD__BENH_AN
	FOREIGN KEY(ID_BA) REFERENCES BENH_AN(ID_BA)
GO

ALTER TABLE DICHVU_SD
	ADD CONSTRAINT fk_DICHVU_SD__HOA_DON
	FOREIGN KEY(ID_HOADON) REFERENCES HOA_DON(ID_HOADON)
GO

ALTER TABLE LICH_LAM_VIEC
	ADD CONSTRAINT fk_LICH_LAM_VIEC__NHA_SI
	FOREIGN KEY(ID_NS) REFERENCES NHA_SI(ID_TAIKHOAN)
GO

ALTER TABLE LICH_DAT_KHAM
	ADD CONSTRAINT fk_LICH_DAT_KHAM__KHACH_HANG
	FOREIGN KEY(ID_KH) REFERENCES KHACH_HANG(ID_TAIKHOAN)
GO

ALTER TABLE LICH_DAT_KHAM
	ADD CONSTRAINT fk_LICH_DAT_KHAM__NHAN_VIEN
	FOREIGN KEY(ID_NV) REFERENCES NHAN_VIEN(ID_TAIKHOAN)
GO

ALTER TABLE LICH_DAT_KHAM
	ADD CONSTRAINT fk_LICH_DAT_KHAM__LICH_LAM_VIEC
	FOREIGN KEY(ID_LLV) REFERENCES LICH_LAM_VIEC(ID_LLV)
GO

------------------------------------------
--RANG BUOC TOAN VEN
------------------------------------------

--Một lịch đặt hẹn phải chọn một lịch nha sĩ với điều kiện lịch nha sĩ chưa có lịch đặt hẹn và ngày phải hợp lệ (không được là ngày trước ngày hiện tại)
create or alter trigger TR_1 on LICH_DAT_KHAM for insert,update
as
	if	not exists	(
						select *
						from inserted as I, LICH_DAT_KHAM as LDK, LICH_LAM_VIEC as LLV
						where	I.ID_LLV is not null
								and I.ID_LLV = LDK.ID_LLV
								and LLV.ID_LLV = LDK.ID_LLV
								and LLV.TRANGTHAI = N'Trống'
					)
	begin
		;throw 50000, N'Lịch làm việc đã đặt không hợp lệ',1
		rollback tran
	end
	else
	begin
		update LICH_LAM_VIEC
		set TRANGTHAI = N'Đã Đặt'
	end
go

--Ngày khám của bệnh án phải là ngày hiện tại hoặc trước đó, nếu vi phạm thì sử dụng ngày hiện tại
create or alter trigger TR_2 on BENH_AN for insert,update
as
	if exists	(
					select *
					from inserted as I
					where	datediff(day,I.NGAYKHAM, getdate()) > 0
				)
	begin
		update BENH_AN
		set NGAYKHAM = getdate()
		from inserted as I
		where BENH_AN.ID_BA = I.ID_BA
	end
go

--Khi thêm thuốc trong đơn thuốc, số lượng không được vượt quá số lượng tồn kho và chưa hết hạn sử dụng.
--Sau khi thêm thuốc vào đơn thuốc, số lượng tồn kho phải giảm theo lượng tương ứng.
create or alter trigger TR_3 on THUOC_SD for insert,update
as
	if exists	(
					select *
					from inserted as I, THUOC as T, SO_LUONG_TON_KHO as SLTK
					where	I.ID_THUOC = T.ID_THUOC
							and T.ID_THUOC = SLTK.ID_THUOC
							and I.SOLUONG <= SLTK.ID_THUOC
				)
	begin
		;throw 50001, N'Số lượng còn lại không đủ cho yêu cầu sử dụng',1
		rollback tran
	end
go

--Nha sĩ không được cập nhật sửa đổi những lịch khám đã có khách đặt
create or alter trigger TR_4 on LICH_LAM_VIEC for insert,delete, update
as
	if exists	(
					select *
					from inserted as I
					where	I.TRANGTHAI != N'Trống'
							or I.ID_LLV in (select LDK.ID_LLV from LICH_DAT_KHAM as LDK)
				)
	begin
		;throw 50002, N'Lịch làm việc đã được đặt',1
		rollback tran
	end
go

--Khi xoá một lịch đặt hẹn, trạng thái của lịch làm việc mà lịch đặt hẹn đó giữ phải được trả lại trạng thái “Trống”
create or alter trigger TR_5 on LICH_DAT_KHAM for delete, update
as
	update LICH_LAM_VIEC
	set TRANGTHAI = N'Trống'
	where ID_LLV not in (select ID_LLV from LICH_DAT_KHAM)

	if exists	(
					select *
					from deleted as D, LICH_LAM_VIEC as LLV
					where	D.ID_LLV = LLV.ID_LLV
							and LLV.TRANGTHAI != N'Trống'
				)
	begin
		update LICH_LAM_VIEC
		set TRANGTHAI = N'Trống'
		from deleted as D
		where	D.ID_LLV = LICH_LAM_VIEC.ID_LLV
	end
go

--Không thêm thuốc vào đơn thuốc đã được tính tiền hoá đơn (ID_HOADON is not null)
create or alter trigger TR_6 on THUOC_SD for insert, delete, update
as
	if exists	(
					select *
					from	inserted as I 
							inner join DON_THUOC as DT on I.ID_DONTHUOC = DT.ID_DONTHUOC
					where	DT.ID_HOADON is not null
				)
		or exists	(
						select *
						from	deleted as D
							inner join DON_THUOC as DT on D.ID_DONTHUOC = DT.ID_DONTHUOC
						where	DT.ID_HOADON is not null
					)
	begin
		;throw 50003, N'Đơn thuốc đã được tính tiền',1
		rollback tran
	end
go