USE QL_NHAKHOA
GO

EXEC sp_addrole 'NHAN_VIEN'
GO

-- thông tin cá nhân ---
CREATE OR ALTER VIEW V_TKNHANVIEN
AS
	SELECT*
	FROM TAI_KHOAN TK
GO

-- Qu?n lý l?ch ??t khám cho b?nh nhân --
CREATE OR ALTER VIEW V_LICHDATKHAM_NHANVIEN 
AS
	SELECT*
	FROM
		LICH_DAT_KHAM
GO
-- LICH LAM VIEC 
CREATE OR ALTER VIEW V_LICHLAMVIEC_NHANVIEN 
AS
	SELECT*
	FROM
		LICH_LAM_VIEC
GO

-- Thanh toán và in hóa ??n cho b?nh nhân -- 
CREATE OR ALTER VIEW V_HOADON_NHANVIEN 
AS
	SELECT *
	FROM HOA_DON
GO

-- Xem danh m?c thu?c --
CREATE OR ALTER VIEW V_DANHMUC_THUOC 
AS
	SELECT
		T.ID_THUOC,
		T.TENTHUOC,
		T.CHIDINH,
		T.NGAYHETHAN,
		T.GIATIEN,
		SLTK.SOLUONG AS SOLUONGTONKHO
	FROM
		THUOC T
	LEFT JOIN
		SO_LUONG_TON_KHO SLTK ON T.ID_THUOC = SLTK.ID_THUOC;
GO

-- XEM THUOCSD 
CREATE OR ALTER VIEW V_DANHMUC_THUOCSD 
AS
	SELECT
		TSD.ID_BA,
		TSD.ID_THUOC,
		TSD.SOLUONG,
		TSD.SOLUONG * T.GIATIEN AS THANHTIEN_THUOC
	FROM
		THUOC_SD TSD
	JOIN 
		THUOC T ON (T.ID_THUOC = TSD.ID_THUOC)
GO

-- XEM DICHVU SD
CREATE OR ALTER VIEW V_DICHVU_SD 
AS
	SELECT *
	FROM
		DICHVU_SD 
GO

GRANT SELECT, UPDATE ON V_TKNHANVIEN TO NHAN_VIEN
GRANT SELECT, UPDATE, INSERT ON V_LICHDATKHAM_NHANVIEN  TO NHAN_VIEN
GRANT SELECT, UPDATE, INSERT ON V_LICHLAMVIEC_NHANVIEN  TO NHAN_VIEN
GRANT SELECT, INSERT ON V_HOADON_NHANVIEN TO NHAN_VIEN
GRANT SELECT ON V_DANHMUC_THUOC TO NHAN_VIEN
GRANT SELECT ON V_DANHMUC_THUOCSD  TO NHAN_VIEN
GRANT SELECT ON V_DICHVU_SD TO NHAN_VIEN
GO
