USE QL_NHAKHOA
GO

-- INSERT --
-- INSERT HOA DON -- 
CREATE OR ALTER PROC SP_NV_LAPHOADON
	@ID_NV VARCHAR(255),
	@ID_BA VARCHAR(255)
AS
BEGIN
    BEGIN TRAN;

    DECLARE @TONGTIEN MONEY
    DECLARE @TONGTIENTHUOC MONEY
    DECLARE @TONGTIENDV MONEY

    SELECT @TONGTIENTHUOC = SUM(THANHTIEN_THUOC)
    FROM V_DANHMUC_THUOCSD 
    WHERE @ID_BA = ID_BA

    SELECT @TONGTIENDV = THANHTIEN
    FROM V_DICHVU_SD
    WHERE ID_BA = @ID_BA

    SET @TONGTIEN = @TONGTIENTHUOC + @TONGTIENDV

    DECLARE @ID_HOADON VARCHAR(255);
    SET @ID_HOADON = 'HD' + REPLACE(CONVERT(VARCHAR, GETDATE(), 112), '-', '') + RIGHT('0000' + CAST((SELECT COUNT(*) + 1 FROM HOA_DON) AS VARCHAR), 4);

    BEGIN TRY
        INSERT INTO V_HOADON_NHANVIEN (ID_HOADON, ID_NV, ID_BA, TONGTIEN, TONGTIENTHUOC, TONGTIENDV)
        VALUES (@ID_HOADON, @ID_NV, @ID_BA, @TONGTIEN, @TONGTIENTHUOC, @TONGTIENDV);

		UPDATE DICHVU_SD
        SET ID_HOADON = @ID_HOADON
        WHERE ID_BA = @ID_BA;
		WAITFOR DELAY '00:00:20' 
        SELECT 
            THUOC.TENTHUOC, 
            THUOC_SD.SOLUONG, 
            THUOC.GIATIEN, 
            THUOC_SD.SOLUONG * THUOC.GIATIEN AS THANHTIEN 
        FROM 
            THUOC_SD
        JOIN 
            THUOC ON THUOC_SD.ID_THUOC = THUOC.ID_THUOC
        WHERE 
            THUOC_SD.ID_BA = @ID_BA;

        COMMIT TRAN;
        PRINT 'Hoá đơn đã được tạo thành công!';
    END TRY
    BEGIN CATCH
        ROLLBACK TRAN;
        PRINT 'Đã xảy ra lỗi trong quá trình xử lý hoá đơn.';
    END CATCH
END
GO

-- xem bang gia thuoc luc ban dau --
SELECT * 
FROM V_DANHMUC_THUOC 
--- CHUC NANG LAP HOA DON NV ---
-- GIA SU THEM MOT LAN KHAM BENH CHO BENH NHAN	 -- 
insert BENH_AN(ID_BA,ID_KH,ID_NS,NGAYKHAM)
values
(cast(NEWID() as varchar(255)),(select ID_TAIKHOAN from TAI_KHOAN where SDT = '012235318'), (select ID_TAIKHOAN from TAI_KHOAN where SDT = '012340078'), '2024-05-01');
go

INSERT INTO THUOC_SD(ID_BA,ID_THUOC,SOLUONG) VALUES
((select top 1 ID_BA from BENH_AN inner join TAI_KHOAN on ID_KH=ID_TAIKHOAN where SDT = '012235318' ORDER BY NGAYKHAM DESC), (select top 1 ID_THUOC from THUOC where TENTHUOC = N'Lisinopril'), 5),
((select top 1 ID_BA from BENH_AN inner join TAI_KHOAN on ID_KH=ID_TAIKHOAN where SDT = '012235318' ORDER BY NGAYKHAM DESC), (select top 1 ID_THUOC from THUOC where TENTHUOC = N'Ibuprofen'),  10),
((select top 1 ID_BA from BENH_AN inner join TAI_KHOAN on ID_KH=ID_TAIKHOAN where SDT = '012235318' ORDER BY NGAYKHAM DESC), (select top 1 ID_THUOC from THUOC where TENTHUOC = N'Omeprazole'), 15);

INSERT INTO DICHVU_SD(ID_DVSD, ID_LOAIDV, THANHTIEN, ID_HOADON, ID_BA) VALUES
(cast(NEWID() as varchar(255)), (SELECT TOP 1 ID_LOAIDV FROM LOAI_DV WHERE TENDV = N'Dịch vụ 1') ,(SELECT TOP 1 GIATIEN FROM LOAI_DV WHERE TENDV = N'Dịch vụ 1'), NULL, (select top 1 ID_BA from BENH_AN inner join TAI_KHOAN on ID_KH=ID_TAIKHOAN where SDT = '012235318'ORDER BY NGAYKHAM DESC) )

--- LAP HOA DON ---
DECLARE @BA VARCHAR(255)
DECLARE @NV VARCHAR(255)
SELECT TOP 1  @BA = ID_BA  FROM BENH_AN BA join TAI_KHOAN TK ON TK.ID_TAIKHOAN = BA.ID_KH WHERE TK.SDT = '012235318' ORDER BY NGAYKHAM DESC
SELECT @NV = ID_TAIKHOAN FROM TAI_KHOAN WHERE SDT = '012345678'

EXEC SP_NV_LAPHOADON @NV, @BA
GO
