use QL_NHAKHOA
go

declare @ID_THUOC VARCHAR(255), @TENTHUOC NVARCHAR(50)

select top 1 @ID_THUOC = TSD.ID_THUOC, @TENTHUOC = THUOC.TENTHUOC
from THUOC_SD as TSD
		inner join BENH_AN as BA on TSD.ID_BA = BA.ID_BA
		inner join TAI_KHOAN as TK on TK.ID_TAIKHOAN = BA.ID_KH
		inner join THUOC on THUOC.ID_THUOC = TSD.ID_THUOC
where TK.SDT = '0888123456'

print @TENTHUOC

exec sp_XOA_TT_THUOC @ID_THUOC
