use QL_NHAKHOA
go

CREATE OR ALTER PROC SP_NV_LAPHOADON
	@ID_NV VARCHAR(255),
	@ID_BA VARCHAR(255)
AS
BEGIN
    BEGIN TRAN;

    DECLARE @TONGTIEN MONEY
    DECLARE @TONGTIENTHUOC MONEY
    DECLARE @TONGTIENDV MONEY

    SELECT @TONGTIENTHUOC = SUM(THANHTIEN_THUOC)
    FROM V_DANHMUC_THUOCSD 
    WHERE @ID_BA = ID_BA

    SELECT @TONGTIENDV = THANHTIEN
    FROM V_DICHVU_SD
    WHERE ID_BA = @ID_BA

    SET @TONGTIEN = @TONGTIENTHUOC + @TONGTIENDV

    DECLARE @ID_HOADON VARCHAR(255);
    SET @ID_HOADON = 'HD' + REPLACE(CONVERT(VARCHAR, GETDATE(), 112), '-', '') + RIGHT('0000' + CAST((SELECT COUNT(*) + 1 FROM HOA_DON) AS VARCHAR), 4);

    BEGIN TRY
        INSERT INTO V_HOADON_NHANVIEN (ID_HOADON, ID_NV, ID_BA, TONGTIEN, TONGTIENTHUOC, TONGTIENDV)
        VALUES (@ID_HOADON, @ID_NV, @ID_BA, @TONGTIEN, @TONGTIENTHUOC, @TONGTIENDV);

		UPDATE DICHVU_SD
        SET ID_HOADON = @ID_HOADON
        WHERE ID_BA = @ID_BA;

		waitfor delay '00:00:10'

        SELECT 
            THUOC.TENTHUOC, 
            THUOC_SD.SOLUONG, 
            THUOC.GIATIEN, 
            THUOC_SD.SOLUONG * THUOC.GIATIEN AS THANHTIEN 
        FROM 
            THUOC_SD
        JOIN 
            THUOC ON THUOC_SD.ID_THUOC = THUOC.ID_THUOC
        WHERE 
            THUOC_SD.ID_BA = @ID_BA;

        COMMIT TRAN;
        PRINT 'Hoá đơn đã được tạo thành công!';
    END TRY
    BEGIN CATCH
        ROLLBACK TRAN;
        PRINT 'Đã xảy ra lỗi trong quá trình xử lý hoá đơn.';
    END CATCH
END
GO