use QL_NHAKHOA
go

CREATE OR ALTER PROC SP_NV_LAPHOADON
	@ID_NV VARCHAR(255),
	@ID_BA VARCHAR(255)
AS
BEGIN
    BEGIN TRAN;

    DECLARE @TONGTIEN MONEY
    DECLARE @TONGTIENTHUOC MONEY
    DECLARE @TONGTIENDV MONEY

    SELECT @TONGTIENTHUOC = SUM(THANHTIEN_THUOC)
    FROM V_DANHMUC_THUOCSD 
    WHERE @ID_BA = ID_BA

    SELECT @TONGTIENDV = THANHTIEN
    FROM V_DICHVU_SD
    WHERE ID_BA = @ID_BA

    SET @TONGTIEN = @TONGTIENTHUOC + @TONGTIENDV

    DECLARE @ID_HOADON VARCHAR(255);
    SET @ID_HOADON = 'HD' + REPLACE(CONVERT(VARCHAR, GETDATE(), 112), '-', '') + RIGHT('0000' + CAST((SELECT COUNT(*) + 1 FROM HOA_DON) AS VARCHAR), 4);

    BEGIN TRY
        INSERT INTO V_HOADON_NHANVIEN (ID_HOADON, ID_NV, ID_BA, TONGTIEN, TONGTIENTHUOC, TONGTIENDV)
        VALUES (@ID_HOADON, @ID_NV, @ID_BA, @TONGTIEN, @TONGTIENTHUOC, @TONGTIENDV);

		UPDATE DICHVU_SD
        SET ID_HOADON = @ID_HOADON
        WHERE ID_BA = @ID_BA;

		waitfor delay '00:00:10'

        SELECT HD.ID_HOADON, DVSD.*
		FROM HOA_DON as HD
			inner join BENH_AN as BA on BA.ID_BA = HD.ID_BA
			inner join DICHVU_SD as DVSD on BA.ID_BA = DVSD.ID_BA
		where	HD.ID_HOADON = @ID_HOADON

		SELECT HD.ID_HOADON, TSD.*, TSD.SOLUONG * THUOC.GIATIEN as THANHTIEN
		FROM HOA_DON as HD
			inner join BENH_AN as BA on BA.ID_BA = HD.ID_BA
			inner join THUOC_SD as TSD on TSD.ID_BA = HD.ID_BA
			inner join THUOC on THUOC.ID_THUOC = TSD.ID_THUOC
		where	HD.ID_HOADON = @ID_HOADON

        COMMIT TRAN;
        PRINT 'Hoá đơn đã được tạo thành công!';
    END TRY
    BEGIN CATCH
        ROLLBACK TRAN;
        PRINT 'Đã xảy ra lỗi trong quá trình xử lý hoá đơn.';
    END CATCH
END
GO